### PR TITLE
generate mock spectra by splitting the sky into healpix pixels

### PR DESCRIPTION
**Pull request by moustakas**
This is not ready to merge (still need to finish the refactor of `desitarget.build.targets_truth`) but I wanted to share the top-level script which splits the DESI tiles into healpix pixels.  Below is some informational output from the script that generates the individual SLURM scripts.  

I still need to test at NERSC to find the right number of jobs per node and total time needed, but comments are welcome.  My goal is to have spectra for the 2% footprint area reprocessed by the end of this weekend so we can turn to the 20% area.  (Is there an .ecsv file for that yet?)

```
(desi) ioannis@atlas:~/repos/desihub/two_percent_DESI% python sprint-healpix-slurm --nside-output-dir 16 --nsuperpix-per-node 8
WARNING:log.py:19:get_logger: desispec.log is deprecated, please use desiutil.log.
INFO:sprint-healpix-slurm:74:main: Processing spectra in healpixels with nside = 64.
INFO:sprint-healpix-slurm:75:main: Number of superpixels (output directories) = 313 with nside = 16.
INFO:sprint-healpix-slurm:76:main: Number of nodes needed = 40 with 8 superpixels per node.
INFO:sprint-healpix-slurm:83:main: Writing ./slurm-16-8-9-10-11-32-43-46-129.sh
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 8 in superpixel 8 (nside = 16) with total area = 6.714 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 5 in superpixel 9 (nside = 16) with total area = 4.196 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 10 in superpixel 10 (nside = 16) with total area = 8.393 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 3 in superpixel 11 (nside = 16) with total area = 2.518 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 2 in superpixel 32 (nside = 16) with total area = 1.679 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 3 in superpixel 43 (nside = 16) with total area = 2.518 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 1 in superpixel 46 (nside = 16) with total area = 0.839 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 15 in superpixel 129 (nside = 16) with total area = 12.589 deg2.
INFO:sprint-healpix-slurm:83:main: Writing ./slurm-16-132-593-596-597-599-639-725-727.sh
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 3 in superpixel 132 (nside = 16) with total area = 2.518 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 6 in superpixel 593 (nside = 16) with total area = 5.036 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 1 in superpixel 596 (nside = 16) with total area = 0.839 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 11 in superpixel 597 (nside = 16) with total area = 9.232 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 5 in superpixel 599 (nside = 16) with total area = 4.196 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 4 in superpixel 639 (nside = 16) with total area = 3.357 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 8 in superpixel 725 (nside = 16) with total area = 6.714 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 8 in superpixel 727 (nside = 16) with total area = 6.714 deg2.
INFO:sprint-healpix-slurm:83:main: Writing ./slurm-16-733-735-768-769-770-771-772-773.sh
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 8 in superpixel 733 (nside = 16) with total area = 6.714 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 4 in superpixel 735 (nside = 16) with total area = 3.357 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 1 in superpixel 768 (nside = 16) with total area = 0.839 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 3 in superpixel 769 (nside = 16) with total area = 2.518 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 5 in superpixel 770 (nside = 16) with total area = 4.196 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 16 in superpixel 771 (nside = 16) with total area = 13.429 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 6 in superpixel 772 (nside = 16) with total area = 5.036 deg2.
INFO:sprint-healpix-slurm:100:main:   Number of healpixels (nside = 64) = 15 in superpixel 773 (nside = 16) with total area = 12.589 deg2.
[snip]
```

### CODE REVIEW

**Comment by sbailey** [comment]
Adding a comment, largely to test notification settings (which weren't being sent...):  Thanks for adding this.  I'm not aware of a 20% ecsv file yet, but testing on 2% would be welcome.

**Comment by moustakas** [comment]
As we work out the NERSC kinks, we should consider adding a few more things to this PR before merging (since it'll likely be the last major update before the Collaboration Meeting).  Some of these are probably pie in the sky on the time scale at play (i.e., next day or two) but I'll list them nevertheless:
* Should we merge #179 first, to use the latest LRG targeting algorithm?
* Should we include at least *one* value of stellar velocity dispersion broadening for the ELG and BGS spectra (more than one is too slow and something we'll tackle at a later date)?
* Should we switch to the Lyman-alpha (mock) skewers that are on-disk?  (Right now we're using the coordinates and redshifts from that mock but generating the Lyman-alpha forest spectra on-the-fly)?
* Should we include DLAs in the Lya forest (see https://github.com/desihub/desisim/pull/220)?

**Comment by sbailey** [comment]
> Should we switch to the Lyman-alpha (mock) skewers that are on-disk? (Right now we're using the coordinates and redshifts from that mock but generating the Lyman-alpha forest spectra on-the-fly)?

Yes, if at all possible we should go back to using the mock skewers.  I had forgotten that we weren't and incorrectly told the Lyman-alpha WG this morning that the 2% survey had full 3D correlations in them and they were glad to hear that and discussed working on measuring BAO during the hackfest day...

> Should we include at least one value of stellar velocity dispersion broadening for the ELG and BGS spectra (more than one is too slow and something we'll tackle at a later date)?

Medium priority.

> Should we merge #179 first, to use the latest LRG targeting algorithm?
> Should we include DLAs in the Lya forest (see desihub/desisim#220)?

Low priority.

**Comment by moustakas** [comment]
This PR has been made obsolete by https://github.com/desihub/desitarget/pull/187 so I'm going to merge to start testing the MPI implementation.

**Pull request merged**
