### PR TITLE
automate minitest

### PR DESCRIPTION
**Pull request by sbailey**
This PR implements two automation improvements to the minitest notebook:

1. When rerunning, it detects which steps have already successfully completed and skips over them, reading in the data necessary for downstream cells.  If all steps have previously succeeded, the entire notebook runs in ~30 seconds.  Just run all cells and it should do the right thing; no need to guess which cells to run or not.  This makes it much easier to resume mid-stream if needed.  This was a leftover request from the original PR review.

2. It directly spawns the multi-node `--qos interactive` jobs and waits for their completion, thus avoiding the previous instructions like "use salloc to get an interactive job and then run these commands...".  If everything runs successfully, a human no longer needs to shepherd the individual steps and the entire notebook can run from start to finish in ~1h45m.

Item (2) needs to be tested for the case where the user sets environment variables in their .bash* or .tcsh* files that the notebook is trying to override; I'm not sure if they will propagate correctly into the srun jobs or not.

This version is still tied to release 17.9 and is incompatible with master due to changes in surveysim progress -> exposures.  @weaverba137 I know you have been working on updating this for master.  Please take a look at this and see if it is easier to merge your changes into this or these changes into your copy.  These changes touched a lot of cells so I'm guessing that it will be easier to re-implement the changes necessary for master into this version of the notebook.  I can do that if you have a working example of the notebook for master and an point me to what changed.  If you don't have a working version yet, the usability improvements in this notebook may be worth starting over again with this as the basis.

### CODE REVIEW

**Comment by weaverba137** [comment]
So far, this notebook is working fine for me, without any modifications.  It's still running, but I'd like to suggest a change right now.  You should include the explicit initialization of the `desisurvey.config.Configuration` object.
```python
from desisurvey.config import Configuration
Configuration.reset()
config = Configuration(os.path.join(twopercentdir, 'mini', 'desisurvey-config.yaml'))
print(config.tiles_file())
```
Note also, that in my notebooks I define an explicit `twopercentdir` variable, which replaces `.`.

**Comment by weaverba137** [comment]
In Cell 29, which starts with `#- Check individual framefile outputs`, the line:
```
hdr = fits.getheader(fmfile, 1)
```
`fits` is not defined anywhere in the notebook.  Did you mean `fitsio`, or `astropy.io.fits`?

**Comment by sbailey** [comment]
Thanks for the testing.

+1 for pre-loading the desisurvey configuration object, which is required for running on master.

The equivalent of `twopercentdir` is `minitestdir = os.getcwd()` set in cell 3.

`fits` is intended to be `astropy.io.fits`.  That worked for me because my default ipython environment includes `from astropy.io import fits` and I forgot to include that explicitly in this notebook.

**Review by weaverba137 — APPROVED** [review]
I've already mentioned a couple of minor problems.  This can be merged after those are fixed.

**Comment by weaverba137** [comment]
I ran through the whole notebook.  Merge after the minor problems already noted are fixed.

I think there is an `from astropy.io import fits` *after* the line that I noted, so I'd move that to the top.

**Pull request merged**
