### PR TITLE
Minitest database

### PR DESCRIPTION
**Pull request by weaverba137**
This PR adds SQLite database loading to the minitest notebook.  This should be merged in conjunction with desihub/desispec#477.

### CODE REVIEW

**Comment by sbailey** [comment]
The notebook has some loading errors for the exposures table:
```
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1158                         parameters,
-> 1159                         context)
   1160             elif not parameters and context.no_parameters:

/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/sqlalchemy/engine/default.py in do_executemany(self, cursor, statement, parameters, context)
    466     def do_executemany(self, cursor, statement, parameters, context=None):
--> 467         cursor.executemany(statement, parameters)
    468 

IntegrityError: UNIQUE constraint failed: obslist.expid
```
I'm not sure if the comment "ignore the return value of setup_db" was meant to indicate ignoring that traceback or not, or whether this is a real problem in the load that needs to be addressed.

I'd prefer if all of the DB loading was done at the end in a separate section of the notebook, even for things like the exposures table that could have been loaded earlier.  It would also be nice to have a few cells showing connecting to the database and extracting some information to demonstrate that the load actually worked.

**Comment by weaverba137** [comment]
What kernel are you running the notebook in?  It needs DESI master.

**Comment by weaverba137** [comment]
And cori is down today, so I can't test this right now.

**Comment by sbailey** [comment]
I was just viewing the one committed to github in the minitest-database branch:

https://github.com/desihub/two_percent_DESI/blob/minitest-database/mini/minitest.ipynb

**Comment by weaverba137** [comment]
Huh, I recall that the exposures table loaded correctly.  That may be left over from an attempt to load it *twice*.

**Comment by weaverba137** [comment]
@sbailey, this is ready for final review.

**Comment by sbailey** [comment]
Looks good; thanks.  Merging now and I'll take back the virtual write lock for further updates.

**Pull request merged**
