### PR TITLE
Minitest instructions

### PR DESCRIPTION
**Pull request by sbailey**
This PR moves the original and mostly incomplete 2% survey instructions into a dc17a subdirectory and introduces a new "mini" subdirectory with a jupyter notebook of instructions for running a mini end-to-end test with a small subset of tiles.  These instructions have been tested with the suite of tags defined in desimodules version 17.9 using jupyter-dev.nersc.gov.

Before merging, could @weaverba137 (or another volunteer) verify that these instructions also work for them and don't rely on something specific to my setup?  (Apologies, Ben, there are bash assumptions throughout the instructions).

Readonly notebook link (but this link will disappear after merging since it will move into master instead of the minitest branch):
https://github.com/desihub/two_percent_DESI/blob/minitest/mini/minitest.ipynb

After merging, I'd like to tag two_percent_DESI as a reference for the 17.9 desi software release, and then continue to use this notebook to test updates to master versions of packages.  In particular, this end-to-end test encountered problems with the desispec pipeline wrappers, redrock memory usage, and z>1.7 QSO template generation.  As those are fixed, these instructions can be updated and simplified.

Steps included in the test:
* selecting a subset of tiles
* running survey simulations for just those tiles
* generating truth spectra tied to mocks for healpix covering those tiles
* fiber assignment
* combining fiber assignment, true spectra, and survey simulations into spectral simulations
  * but not pixel-level simulations
* running the spectro pipeline starting from uncalibrated frame files
  * skips PSF estimatation and spectral extraction steps
* regrouping spectra by healpix
* running redrock

ALAS not yet included here: running standard QA tools.  I'd like to get that in, but this has been lingering too long already so I'd like to get other eyes and testers on it before it drags out more.

Future 2% survey redo instructions should go into a different subdirectory, e.g. dc17b.

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, I'm having trouble with the Jupyter notebook server at NERSC.

**Review by weaverba137 — CHANGES_REQUESTED** [review]
I tried running the notebook myself, and ran into one error.  At the "Run the spectro pipeline stage", the batch script generation appears to have failed silently.  The command ran in the cell, but the batch scripts did not actually get written.

In addition I have these suggestions:

1. Make the commands that require MPI more robust, for example, instead of `--config select-mock-targets.yaml`, use `$TWO_PERCENT_DESI/mini/select-mock-targets.yaml`.
2. After running the notebook, my two_percent_DESI checkout had extraneous files in it.  These files should be written directly to `$SCRATCH` if possible.  If it is absolutely necessary that they be written in the checkout, then they should be added to the `.gitignore` file.
3. Support tcsh.  I can provide the tcsh commands, and a simple switch based on `os.environ['SHELL']`.

I have not yet run the notebook with the latest changes to `Progress.get_exposures()` and with (as-yet potential) changes to `wrap-newexp`.

**Comment by weaverba137** [comment]
Add `-A desi` to all batch scripts.

**Comment by sbailey** [comment]
Good suggestions.  For the batch script generation, what notebook output do you get from the cell that runs
```python
from desispec.scripts import pipe_prod
args = pipe_prod.parse('--nersc_host cori --nersc_queue debug --fakepix'.split())
pipe_prod.main(args)
```
Do you get anything in $DESI_SPECTRO_REDUX/$SPECPROD?  (if not, please confirm what your $DESI_SPECTRO_REDUX/$SPECPROD is).

What happens if you run this from the command line?
```console
# setup code and environment with tcsh equivalent of output of cell 2, then...
desi_pipe --nersc_host cori --nersc_queue debug --fakepix
```
Does that write any batch scripts to $DESI_SPECTRO_REDUX/$SPECPROD/run/scripts?

**Comment by weaverba137** [comment]
Here is the output from `pipe_prod.main(args)`:

```
Working with production /global/cscratch1/sd/bweaver/desi/dev/end2end/spectro/redux/mini :
  Updating plans ...
  Creating setup.sh ...
  Selecting nights ...
  Finding max processes supported by workers ...
    bootstrap : 1 processes per task
    psf : 20 processes per task
    psfcombine : 1 processes per task
    extract : 20 processes per task
    fiberflat : 1 processes per task
    sky : 1 processes per task
    stdstars : 1 processes per task
    fluxcal : 1 processes per task
    calibrate : 1 processes per task
    redshift : 16 processes per task
  Generating scripts ...
```
That's it.

I'll run the command line tests shortly.

**Comment by weaverba137** [comment]
PS, it looks like I have a normal subdirectory layout in `$DESI_SPECTRO_REDUX/$SPECPROD`:
```
$ ls /global/cscratch1/sd/bweaver/desi/dev/end2end/spectro/redux/mini
calib2d/    exposures/  plan/       run/        setup.sh    spectra-64/
```
run/scripts contains:
```
ls /global/cscratch1/sd/bweaver/desi/dev/end2end/spectro/redux/mini/run/scripts
redshift.sh    redshift.slurm  run_shell.sh   run_slurm.sh   spectra.sh     spectra.slurm
```

**Comment by weaverba137** [comment]
I ran `desi_pipe --nersc_host cori --nersc_queue debug --fakepix` on the command-line and got the same output, and again, no scripts in the run/scripts directory (besides those already listed above).

**Comment by weaverba137** [comment]
Another clean-up task to think about.  Currently, the notebook is success-oriented, that is, every cell assumes that all the previous cells succeed.  So if a step fails halfway through, you can't just log out, go home, log in, and restart the notebook at the step that failed, because subsequent cells depend on variables defined in cells before the step that failed, so basically all the previous cells have to be re-run.  Maybe there's no easy way to fix this, but one could at least think about defining all the most critical Python variables in one cell, and just re-run that one cell, then re-run the cell that failed.

Concrete example, and not even a real failure.  I got to the wrap-newexp step, it ran successfully, but it was the end of the day, so I closed the notebook and went home.  I wanted to continue working on the notebook at home, so I started the pipeline step.  That also ran to completion.  Then the very next cell "Check that we got the expected results" contains variables that are defined at the beginning of the notebook, and some of the cells where those variables are defined may be overwriting files that were already successfully generated.

So maybe what is required is a clean separation of cells where global variables are defined from cells that create files, so that one can define the variables without touching any files.

**Comment by sbailey** [comment]
For the record: offlist Ben and I debugged that his missing files were because his interactive job environment configuration in his .tcshrc.ext (or similar) file was undoing the configuration set on the login node before requesting an interactive job.  This caused the files to be sent to /project instead of /scratch.

The instructions need to be updated to set the necessary environment *after* getting the interactive job rather than before so that they are robust to whatever the user may have in their login dot files.

Another improvement would be to add more intermediate steps to verify that the expected files were generated; Ben's problem with the pipeline planning was actually caused several steps earlier, but nothing complained about the missing files and `desi_pipe` exited cleanly thinking it had nothing to do because it couldn't find any inputs.  That could have been caught earlier, and `desi_pipe` itself should print an informative error if it can't find any inputs.

Agreed about the difficulty of restarting from scratch without rerunning a bunch of steps.  It is possible to run a subset of cells to regain the important variables, but it certainly isn't obvious which ones.  In the meantime, note that if you save the notebook and close the browser window, you can reconnect to the notebook later via the "Running notebooks" jupyter tab and keep going where you left off.  I have found that to be fairly robust but not perfect.  I have had much worse luck with just closing my laptop without first closing the browser; when I come back the notebook kernel has often died.

**Comment by weaverba137** [comment]
Another potential problem I've noticed: the estimated runtimes for the MPI jobs may be optimistic.  This is not only an annoyance, because it takes longer to run the notebook than advertised, but in some cases, two MPI jobs run in the same interactive session, which is limited to 30 minutes.  If the jobs take even a little bit longer than advertised, the interactive session will time out before the second job is done.

**Comment by weaverba137** [comment]
PS, is there a standard estimate for how long it takes to run the notebook in its entirety?  I'm finding that if I start it from the beginning around 14:00 or 15:00, it's the end of the day before the notebook finishes.  Unfortunately afternoons are usually the best time for me to do things like this.  Mornings tend to be filled with meetings & telecons.

**Comment by weaverba137** [comment]
I've finally got all the way through the notebook, although let me emphasize, this is with only the existing *tagged* versions in desimodules/17.9.  I have not tried this notebook with any changes to *e.g.*, `Progress.get_exposures()` or anything database-related at all.

However, to get through the notebook, I did have to make some changes to my own copy, for example to support tcsh, and to explicitly run all batch computations on the desi repo (`-A desi`).  What is the best way to get these changes back into the notebook?

**Comment by sbailey** [comment]
Thanks for this testing.  If your tcsh changes use `$SHELL` or equivalent to auto-detect and provide bash-vs-tcsh commands, please go ahead and commit your notebook to this branch, and then I'll pick up from there to add the other requested changes and cleanup.  Adding `-A desi` throughout is fine too.

A few other comments:

The interactive jobs with `--qos interactive` can be up to 4 hours long; they are not limited to 30 minutes though that is what is used in most of the examples.  It sounds like you tried to fit `select_mock_targets`, `wrap_newexp`, and `wrap_fastframe` all into a single job.  That is reasonable, but in practice I just grabbed a new interactive job for each step since the `--qos interactive` turnaround is usually quite good, and I was thinking/typing in between each of those steps.

I agree the overall end-to-end time is longer than the hope of running within an hour or so, but I've never done an end-to-end timing test that didn't also involve pauses to update docs or code. Steps that I found to be longer than ~15 minutes:
* waiting in the queue for the spectro pipeline jobs to start (very variable)
* spectral regrouping (40 min)
* redshift fitting (I forget how long; less than 2 hours)

I think everything else fits within an hour combined, but there is some waiting around for those other steps.

**Comment by weaverba137** [comment]
For the record, I only ran multiple MPI jobs in one interactive session because the notebook *explicitly instructs you to*. This is for the combination `wrap-newexp`, `wrap-fastframe`.  You can search for the text:
```
#- From the same interactive job where you ran wrap-newexp, run this:
```
In all other cases, I started a new interactive session for every MPI job.

**Comment by sbailey** [comment]
For me, `wrap-newexp` took 7.4 minutes and `wrap-fastframe` took 9.6 minutes, so that they easily together fit within the 30 minute window allocated for the job.  If they took much longer than that for you, let me know.

**Comment by weaverba137** [comment]
In one case, I think `wrap-newexp` took a very long time to start up, and by the time it was finished, `wrap-fastframe` did not have time to finish.  In other cases, I've seen `wrap-newexp` take ~9-10 minutes.

**Comment by weaverba137** [comment]
Just pushed my version of the notebook.

**Comment by sbailey** [comment]
I've updated the notebook with most of the changes requested by @weaverba137.  

Contributed by him directly:
* support for tcsh
* `salloc -A desi` for users that don't have default desi repo
* set environment in job instead of inheriting from login node, in case .dot files clobber some variable
* .gitgnore generated files

Added:
* more intermediate checks so that failures of any steps are noticed immediately after that step
* even smaller test to run faster, though it still takes ~2 hours total
* tweaks to `wrap-redrock` for robustness
* general cleanup of instructions, e.g. deriving full path to two_percent_DESI/mini and including that in the cut-and-paste instructions instead of "cd to wherever you checked out the code..."

The item that is still a pain is how to recover mid-stream if the notebook died overnight and you need to continue from step N but it requires variables defined earlier, without having to rerun all previous steps.  This is a bit tricky because some of those variables are read in from outputs (e.g. the exposures list from surveysim) and can't just be defined in cell 1 as a one-stop-shop for recovering.

I suggest that we punt this "recover mid-stream" feature request to a later update, and make final review + corrections + merge + two_percent_DESI/17.9 tag now.  In the meantime you can still pause overnight by saving the notebook and closing your window, and then returning to jupyter-dev.nersc.gov later.  I find that more robust than leaving the window open and closing my laptop, which often seems to kill the kernel for unknown reasons.

**Review by weaverba137 — APPROVED** [review]

**Comment by weaverba137** [comment]
Let's get these merged, so we can easily create new branches.

**Pull request merged**
